//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedControlNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int InventarioID { get; set; }
        public Nullable<int> NumeroActivo { get; set; }
        public string Nombre { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaDeCompra { get; set; }
        public Nullable<int> EspecialidadID { get; set; }
        public Nullable<int> ConsultorioID { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Especialidad Especialidad { get; set; }
    }
}
